/*

 SPACESHIP252.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0x02,0x02,0x05,0x07,0x03,0x03,0x05,0x07,
  0x09,0x0F,0x09,0x0F,0x09,0x0F,0x09,0x0F
};

/* End of SPACESHIP252.C */
